trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  LT_USERNAME: "user"
  LT_ACCESS_KEY: "key"

steps:
- script: |
    mvn clean install
    mvn test -P android-single
  displayName: 'Maven Build'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'drop'
    publishLocation: 'Container'
